source 'https://rubygems.org'
ruby '2.1.1'

gem 'rails', '4.1.2'
gem 'pg'
gem 'unicorn'
gem 'unicorn-rails'

gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'spring', group: :development

gem 'active_model_serializers'
gem 'dotenv-rails'
gem 'octokit'

group :production do
  gem 'rails_12factor'
end

group :test do
  gem 'coveralls', require: false
  gem 'rspec-rails', '~> 3.0.0'
  gem 'shoulda-matchers', require: false
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'pry-rails'
end
